### ISSUE TITLE
The language file for Chinese traditional(zh_TW)

### ISSUE THREAD

**Issue by zhtw2013** [edrflt/tabber#2]
The language file for Chinese traditional(zh_TW)
[zh_TW.zip](https://github.com/edrflt/tabber/files/1342425/zh_TW.zip)

**Comment by edrflt** [comment]
I made a new internationalisation system for Tabber's next version [see here](https://github.com/edrflt/tabber_i18n/)
It will download last translations on tabber_i18n repository in order to make them independant of the software.
This will allow people to improve internationalisation without having to wait for updates.
I added yours and it will get released with the new version soon.
Thanks a lot !
